class Legendslist {
  static final List<Map<String, String>> legends = [
    {"name": "Bodvar", "image": "assets/bodvar.png"},
    {"name": "Cassidy", "image": "assets/cassidy.png"},
    {"name": "Orion", "image": "assets/orion.png"},
    {"name": "Lord Vraxx", "image": "assets/lord vraxx.png"},
    {"name": "Gnash", "image": "assets/gnash.png"},
    {"name": "Lucien", "image": "assets/lucien.png"},
    {"name": "Hattori", "image": "assets/hattori.png"},
    {"name": "Sir Roland", "image": "assets/sir roland.png"},
    {"name": "Scarlet", "image": "assets/scarlet.png"},
    {"name": "Thatch", "image": "assets/thatch.png"},
    {"name": "Ada", "image": "assets/ada.png"},
    {"name": "Sentinel", "image": "assets/sentinel.png"},
    {"name": "Teros", "image": "assets/teros.png"},
    {"name": "Red Raptor", "image": "assets/redraptor.png"},
    {"name": "Ember", "image": "assets/ember.png"},
    {"name": "Brynn", "image": "assets/brynn.png"},
    {"name": "Asuri", "image": "assets/asuri.png"},
    {"name": "Barraza", "image": "assets/barraza.png"},
    {"name": "Ulgrim", "image": "assets/ulgrim.png"},
    {"name": "Azoth", "image": "assets/azoth.png"},
    {"name": "Koji", "image": "assets/koji.png"},
    {"name": "Diana", "image": "assets/diana.png"},
    {"name": "Jhala", "image": "assets/jhala.png"},
    {"name": "Loki", "image": "assets/loki.png"},
    {"name": "Kor", "image": "assets/kor.png"},
    {"name": "Wu Shang", "image": "assets/wu shang.png"},
    {"name": "Val", "image": "assets/val.png"},
    {"name": "Ragnir", "image": "assets/ragnir.png"},
    {"name": "Cross", "image": "assets/cross.png"},
    {"name": "Mirage", "image": "assets/mirage.png"},
    {"name": "Sidra", "image": "assets/sidra.png"},
    {"name": "Xull", "image": "assets/xull.png"},
    {"name": "Munin", "image": "assets/munin.png"},
    {"name": "Thor", "image": "assets/thor.png"},
    {"name": "Petra", "image": "assets/petra.png"},
    {"name": "Fait", "image": "assets/fait.png"},
    {"name": "Tezca", "image": "assets/tezca.png"},
    {"name": "Seven", "image": "assets/seven.png"},
    {"name": "Rayman", "image": "assets/rayman.png"},
    {"name": "Dusk", "image": "assets/dusk.png"},
    {"name": "Lin Fei", "image": "assets/lin fei.png"},
    {"name": "Zariel", "image": "assets/zariel.png"},
    {"name": "Jaeyun", "image": "assets/jaeyun.png"},
    {"name": "Onyx", "image": "assets/onyx.png"},
    {"name": "Jiro", "image": "assets/jiro.png"},
    {"name": "Volkov", "image": "assets/volkov.png"},
    {"name": "Kaya", "image": "assets/kaya.png"},
    {"name": "Caspian", "image": "assets/caspian.png"},
    {"name": "Isaiah", "image": "assets/isaiah.png"},
    {"name": "Vector", "image": "assets/vector.png"},
    {"name": "King Zuva", "image": "assets/king zuva.png"},
    {"name": "Vivi", "image": "assets/vivi.png"}
  ];
}
